name: sil
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  flutter_native_splash: ^2.4.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  logger: ^2.3.0
  provider: ^6.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_gen_runner: ^5.5.0+1

flutter_gen:
  output: lib/core/consts/gen/
  integrations:
    flutter_svg: true
    lottie: true

flutter_native_splash:
  color: "#058071"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#058071"
    image: assets/images/logo.png

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  