name: nadarchitecture
description: You can create a clean structure and benefit from its features
version: 1.0.16
homepage: https://github.com/yusufnadar/nadarchitecture


environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  flutter_native_splash: ^2.4.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  logger: ^2.3.0
  provider: ^6.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_gen_runner: ^5.5.0+1


flutter:
  uses-material-design: true
  generate: true

